trigger:
- master

pool:
  name: BuildAgentOnPrem

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo bahur

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'

- task: NuGetAuthenticate@1
  inputs:
    nuGetServiceConnections: 'Public Proget Server - Licensed feed - NuGetAuthenticate'

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'install IgniteUI.Blazor.Documents.Core  -Version 23.1.37 -DependencyVersion Ignore'