trigger:
- master

pool:
  vmImage: 'windows-latest'


steps:
- task: CmdLine@2
  inputs:
    script: |
      echo bahur

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'nuget sources Add -Name "PublicProGet" -Source https://packages.infragistics.com/nuget/licensed/'

- task: NuGetAuthenticate@1
  inputs:
    nuGetServiceConnections: 'Public Proget Server - Licensed feed - NuGetAuthenticate'



- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'install IgniteUI.Blazor.Documents.Core.Trial  -Version 23.1.37 -DependencyVersion Ignore'