trigger:
- master

pool:
  name: BuildDeployment
  demands:
  - Agent.ComputerName -equals S0103BLD1P

steps:
- task: PowerShell@2
  displayName: 'Generate NuGet.config for IG ProGet NuGet feed'
  inputs:
    targetType: 'inline'
    script: |
      dotnet new nugetconfig --force
      dotnet nuget add source http://proget.infragistics.local:81/nuget/IgniteUINuGet/ --name "IG ProGet NuGet" --allow-insecure-connections
      # Manually add the allowInsecureConnections attribute to the nuget.config file
      $nugetConfigPath = "$(Build.SourcesDirectory)\NuGet.config"
      [xml]$nugetConfig = Get-Content $nugetConfigPath
      $nugetConfig.configuration.packageSources.add | Where-Object { $_.name -eq "IG ProGet NuGet" } | ForEach-Object { $_.allowInsecureConnections = "true" }
       # Add credentials to the nuget.config file
      $packageSourceCredentials = $nugetConfig.CreateElement("packageSourceCredentials")
      $source = $packageSourceCredentials.CreateElement("IG ProGet NuGet")
      $add = $source.CreateElement("add")
      $add.SetAttribute("key", "Username")
      $add.SetAttribute("value", "$(IG_Nuget_Feed_Username)")
      $source.AppendChild($add)
      $add = $source.CreateElement("add")
      $add.SetAttribute("key", "ClearTextPassword")
      $add.SetAttribute("value", "$(IG_Nuget_Feed_Password)")
      $source.AppendChild($add)
      $packageSourceCredentials.AppendChild($source)
      $nugetConfig.configuration.AppendChild($packageSourceCredentials)
      $nugetConfig.Save($nugetConfigPath)
    failOnStderr: true
    showWarnings: true
    workingDirectory: '$(Build.SourcesDirectory)'
- task: CmdLine@1
  displayName: 'Run dotnet in blazor app'
  inputs:
    filename: dotnet
    arguments: restore
    workingFolder: '$(Build.SourcesDirectory)\app'
- task: CmdLine@1
  displayName: 'Run dotnet in blazor app'
  inputs:
    filename: dotnet
    arguments: 'build --force'
    workingFolder: '$(Build.SourcesDirectory)\app'
- task: Npm@0
  displayName: 'npm install'
  inputs:
    cwd: '$(Build.SourcesDirectory)'
- task: CmdLine@1
  displayName: 'npm run build'
  inputs:
    filename: npm
    arguments: 'run build'
- task: ArchiveFiles@1
  displayName: 'Archive files '
  inputs:
    rootFolder: '$(Build.SourcesDirectory)/_site'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/IgniteUIBlazorAPIDocfx.zip'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: docsAPISite'
  inputs:
    ArtifactName: docsAPISite
    publishLocation: FilePath
    TargetPath: '\\infragistics.local\igfiles\Builds\Blazor\$(Build.BuildNumber)'