trigger:
- master

pool:
 name: BuildAgentOnPrem


steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'sources Remove -Name "IG ProGet IgniteUINuGet - Staging"'

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'sources Add -Name "IG ProGet IgniteUINuGet - Staging" -Source http://proget.infragistics.local:81/nuget/IgniteUINuGet/'

- task: NuGetAuthenticate@1
  inputs:
    nuGetServiceConnections: 'IG ProGet IgniteUINuGet - Staging'

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'install IgniteUI.Blazor.Documents.Core  -Version 23.1.37 -DependencyVersion Ignore'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.csproj'
    feedsToUse: 'config'
    externalFeedCredentials: 'IG ProGet IgniteUINuGet - Staging'

- task: CmdLine@1
  displayName: 'Run dotnet in blazor app'
  inputs:
    filename: dotnet
    arguments: 'build --force'
    workingFolder: '$(Build.SourcesDirectory)\app'

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'

- task: Npm@0
  displayName: 'npm install'
  inputs:
    cwd: '$(Build.SourcesDirectory)'
- task: CmdLine@1
  displayName: 'npm run build'
  inputs:
    filename: npm
    arguments: 'run build'
