<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
      <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IgniteUI.Blazor" Version="25.2.83" />
    <PackageReference Include="IgniteUI.Blazor.Documents.Core" Version="25.2.83" />
    <PackageReference Include="IgniteUI.Blazor.Documents.Excel" Version="25.2.83" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.2" PrivateAssets="all" />
  </ItemGroup>

    <ItemGroup>
        <Content Include="$(NuGetPackageRoot)\IgniteUI.Blazor\25.2.83\lib\net6.0\IgniteUI.Blazor.xml">
            <Link>IgniteUI.Blazor.xml</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="$(NuGetPackageRoot)\IgniteUI.Blazor.Documents.Core\25.2.83\lib\net6.0\IgniteUI.Blazor.Documents.Core.xml">
            <Link>IgniteUI.Blazor.Documents.Core.xml</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="$(NuGetPackageRoot)\IgniteUI.Blazor.Documents.Excel\25.2.83\lib\net6.0\IgniteUI.Blazor.Documents.Excel.xml">
            <Link>IgniteUI.Blazor.Documents.Excel.xml</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
